# Generated by Django 4.1.6 on 2023-02-15 15:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_remove_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[480, 360], upload_to='authors'),
        ),
    ]
