# Generated by Django 4.1.6 on 2023-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='game_thumbnails/')),
                ('developer', models.CharField(max_length=100)),
            ],
        ),
    ]
